### ISSUE TITLE
flutter_sheet_localization_generator is not supporting intl ^0.17.0

### ISSUE THREAD

**Issue by uc-dve** [aloisdeniel/flutter_sheet_localization#39]
Please update package to support latest version of flutter.

```
Because flutter_sheet_localization_generator >=2.0.0 depends on intl ^0.16.1 and my_project depends on intl ^0.17.0, flutter_sheet_localization_generator >=2.0.0 is forbidden.

So, because my_project depends on flutter_sheet_localization_generator ^2.1.2, version solving failed.
pub get failed (1; So, because my_project depends on flutter_sheet_localization_generator ^2.1.2, version solving failed.)
```

**Comment by JonathanRhein** [comment]
For me it is neither working... with intl 0.17.0

**Comment by aloisdeniel** [comment]
I published a `3.0.0` version yesterday with null-safety support and upgraded dependencies. 

Let me know after upgrading if it works for you!

**Comment by JonathanRhein** [comment]
ok, I still get:

[INFO] Running build...
[INFO] 1.0s elapsed, 18/19 actions completed.
[INFO] 5.2s elapsed, 18/19 actions completed.
[INFO] flutter_sheet_localization_generator:flutter_sheet_localization on lib/localizations.dart:Downloading csv from Google sheet url "https://docs.google.com/spreadsheets/d/1-L8ITusCidVGIV6DZeYQASaz_2GjUrH_yytKPVX8WMI/export?format=csv&id=1-L8ITusCidVGIV6DZeYQASaz_2GjUrH_yytKPVX8WMI&gid=0" ...
[INFO] 6.4s elapsed, 18/19 actions completed.
[WARNING] flutter_sheet_localization_generator:flutter_sheet_localization on lib/localizations.dart:
Missing "part 'localizations.g.dart';".
[INFO] Running build completed, took 6.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 36ms

[INFO] Succeeded after 6.9s with 0 outputs (38 actions)

What am I doing wrong?

**Comment by JonathanRhein** [comment]
I got the problem: There is a typo in the code you provide for the localizations.dart file, it misses an "s" in the end of

`part 'localization.g.dart';`

It should be:
`part 'localizations.g.dart';`

Maybe you can fix this in your readme?

**Comment by aloisdeniel** [comment]
The file is named `localization.dart` in the readme. :)

![image](https://user-images.githubusercontent.com/7687231/111686462-638aa780-8829-11eb-8c38-a3833024320d.png)
